services:
  spotifm:
    image: waveplate/spotifm:latest
    container_name: spotifm
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "3443:3443"
      - "8898:8898"
    volumes:
      # - ./config.toml:/config/config.toml:ro
      # - ./playlists:/root/.local/share/spotifm/playlists:rw
      # - ./player:/app/player:ro
      - ${HOME}/.cache/spotifm:/root/.cache/spotifm:rw
      - ${HOME}/.cache/ncspot:/root/.cache/ncspot:ro
      - ${HOME}/.local/share/spotifm:/root/.local/share/spotifm

  spotifm-ephemeral:
    image: waveplate/spotifm:latest
    container_name: spotifm-ephemeral
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "3443:3443"
      - "8898:8898"

